linters:
  disable-all: true
  enable:
    - revive
    - govet
    - errcheck
    - ineffassign
    - typecheck
    - gosec
    - gofumpt
    - gosimple
    - unused
    - staticcheck
    - gochecknoinits
    - makezero
    - whitespace
    - gci # раз уже настраиваем gci, имеет смысл его включить

  # НОВЫЙ способ исключать директории (вместо run.skip-dirs)
  exclusions:
    paths:
      # регулярки; ^tests/ означает "всё внутри каталога tests"
      - ^tests/
      - ^dev/

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - default
    skip-generated: true
    # правильное имя ключа — no-inline-comments (во множественном числе)
    no-inline-comments: true
  revive:
    rules:
      - name: var-naming
        disabled: true
